############ Large language model config ############
OPENAI_KEY: "sk-xxxxxx" # 'sk-xxxxxx'
DECISION_MODEL: "LoRALlama1:latest"
PREDICT_MODEL: "predictLlama:latest"
OPENAI_API_BASE: "http://localhost:11434/v1"
############### settings ############
SUMO_HOME: '' # the path to the folder where the sumo,sumo-gui
episodes_num: 50 # run episodes
result_folder: 'results/Lorallama7B_predict_result'
simulation_duration: 2000 # step
all_vehicles_decision: False # To save simulation time, you can choose to make decisions only on the vehicle at the front of the lane, and the other vehicles will default to IDLE